name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.5.0
          use-dotnet: false

      - name: Build addon
        run: scripts/build.sh

      - name: Upload build artifacts (for debugging in Actions UI)
        uses: actions/upload-artifact@v4
        with:
          name: addon-zip
          path: out/*.zip
          if-no-files-found: error
          overwrite: true

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write   # required to create releases

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: addon-zip
          path: out

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/*
